### ISSUE TITLE
[Colab] Unable to install Python packages in Swift notebook

### ISSUE THREAD

**Issue by rahulbhalley** [google/swift-jupyter#108]
I cannot run the following code:
```
!pip --version
```

Not even % magic is working. I get the following error:
```
error: <Cell 13>:1:2: error: cannot find 'pip' in scope
!pip
 ^~~
```

**Comment by BradLarson** [comment]
You could try using the `%system` directive (described [here](https://github.com/google/swift-jupyter/pull/66)) within the first cell to install any prerequisites for the notebook you need. That directive was primarily intended for installation of binaries needed before any Swift package could be installed, but might be useful for this as well.

Otherwise, SwiftAI has a `shell()` command implemented [here](https://github.com/fastai/fastai_dev/blob/master/swift/FastaiNotebook_00_load_data/Sources/FastaiNotebook_00_load_data/00_load_data.swift#L22) that can run post-install commands like this via `"/bin/pip".shell("install package")`. I may not have the path and arguments right on that, but you get the general idea.

**Comment by rahulbhalley** [comment]
Thanks!
